name: beads
authors:
- Maxim Zaks <maxim.zaks@gmail.com>
description: This implementation covers two concepts. Beads Sequence - append only data structure which applies bit packing technuques to appended values. Beads Bracelet - a strategy to serialise a complex object as Beads Sequence.
homepage: https://github.com/beads-data-structure/beads_dart
version: 0.1.1

environment:
  sdk: '>=1.24.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  test: '>=0.12.24+2 <2.0.0'
  test_coverage: ^0.2.0